### ISSUE TITLE
Adding `action_results` to the `ABI` struct

### ISSUE THREAD

**Issue by aaroncox** [wharfkit/antelope#84]
This field (and potentially others) are missing from the ABI struct definition, causing them to not be serialized and included in transaction data. 

This field needs to be added in and we should determine if other fields are missing - adding them as well.

Conversation starts here on Telegram: https://t.me/wharfkit/1822

**Comment by david-at-greymass** [comment]
PR created here: https://github.com/wharfkit/antelope/pull/85

**Comment by david-at-greymass** [comment]
-
