### ISSUE TITLE
how to check if an account is inactive

### ISSUE THREAD

**Issue by dev-dantealighieri** [wharfkit/antelope#97]
when i was checking the internet i saw something like this: 'You can’t delete account but you could undelegate all staked EOS and effectively leave that account inactive.'

how can i check if an account is inactive? is this means if an account doesn't have any eos, its not active? or is there any other check i should do?

**Comment by aaroncox** [comment]
From the perspective of the blockchain - every account always exists and could be "active" at any point. There's no "inactive" state for an account from this perspective. 

If you want to apply a subjective view of what you'd consider "inactive", you could use any number metrics such as their token balance, their staked tokens, the last time they performed a transaction, etc. That's up to you though and your opinion on what's active or not, based on what you feel makes it "active".

**Comment by dev-dantealighieri** [comment]
thank you!
